(function() {
    // Perl helper used by the 0.2.x lookup pipeline.
    //
    // It locates a module in the selected interpreter's @INC without loading
    // the module, finds the POD heading/item that best matches a CodeIntel
    // symbol, extracts only that block, and renders it with Pod::Simple::Text.
    // A miss exits with code 3 and a diagnostic that perldoc.js recognizes as
    // a normal fallback condition.
    this.PERL_SOURCE = [
        "use strict;",
        "use warnings;",
        "use Pod::Simple::Text;",
        "",
        "my ($module, $symbol, $owner) = @ARGV;",
        "$owner = $module unless defined $owner && length $owner;",
        "exit 64 unless defined $module && defined $symbol;",
        "",
        "(my $rel = $module) =~ s!::!/!g;",
        "my @rels = ($rel . '.pm', $rel . '.pod');",
        "my $file;",
        "INC: for my $inc (@INC) {",
        "    next if ref $inc;",
        "    for my $candidate (@rels) {",
        "        my $path = $inc . '/' . $candidate;",
        "        if (-f $path) { $file = $path; last INC; }",
        "    }",
        "}",
        "unless ($file) {",
        "    print STDERR qq{No module found for \"$module\".\\n};",
        "    exit 3;",
        "}",
        "",
        "open my $fh, '<', $file or do {",
        "    print STDERR qq{Cannot read POD source for \"$module\": $!\\n};",
        "    exit 2;",
        "};",
        "my @lines = <$fh>;",
        "close $fh;",
        "",
        "sub plain {",
        "    my ($text) = @_;",
        "    $text = '' unless defined $text;",
        "    $text =~ s/[A-Z]<([^<>]*)>/$1/g for 1 .. 4;",
        "    $text =~ s/E<lt>/</g;",
        "    $text =~ s/E<gt>/>/g;",
        "    $text =~ s/E<sol>/\\//g;",
        "    $text =~ s/E<verbar>/|/g;",
        "    $text =~ s/\\s+/ /g;",
        "    $text =~ s/^\\s+|\\s+$//g;",
        "    return $text;",
        "}",
        "",
        "sub score {",
        "    my ($text, $symbol, $module, $owner) = @_;",
        "    my $p = plain($text);",
        "    return 100 if $p eq $symbol;",
        "    return 95 if $p =~ /^\\Q$symbol\\E(?:\\s|\\(|$)/;",
        "",
        "    # Qualified headings such as CPAN::Module::userid() must not be",
        "    # mistaken for the same-named method on CPAN::Index.  Accept an",
        "    # explicit class prefix only when it matches the selected owner",
        "    # (or the exact module currently being searched).",
        "    if ($p =~ /([A-Za-z_]\\w*(?:::\\w+)*)::\\Q$symbol\\E(?:\\s|\\(|$)/) {",
        "        my $prefix = $1;",
        "        return 94 if $prefix eq $owner;",
        "        return 92 if $prefix eq $module && $module eq $owner;",
        "        return 0;",
        "    }",
        "",
        "    # Object-style headings ($obj->method) are unqualified and are",
        "    # safe inside the module source being inspected.",
        "    return 90 if $p =~ /->\\Q$symbol\\E(?:\\s|\\(|$)/;",
        "    return 80 if $p =~ /(^|[^A-Za-z0-9_])\\Q$symbol\\E([^A-Za-z0-9_]|$)/;",
        "    return 0;",
        "}",
        "",
        "my @hits;",
        "my $in_pod = 0;",
        "for (my $i = 0; $i < @lines; $i++) {",
        "    my $line = $lines[$i];",
        "    if ($line =~ /^=(?!cut\\b)\\w+/) { $in_pod = 1; }",
        "    if ($line =~ /^=cut\\b/) { $in_pod = 0; next; }",
        "    next unless $in_pod;",
        "    next unless $line =~ /^=(head([1-4])|item)\\s+(.*)$/;",
        "    my ($kind, $level, $text) = ($1, $2, $3);",
        "    my $s = score($text, $symbol, $module, $owner);",
        "    push @hits, { index => $i, kind => $kind, level => ($level || 0), score => $s, text => $text } if $s;",
        "}",
        "",
        "unless (@hits) {",
        "    print STDERR qq{No symbol POD found for \"$symbol\" in \"$module\" for owner \"$owner\".\\n};",
        "    exit 3;",
        "}",
        "",
        "@hits = sort { $b->{score} <=> $a->{score} || $a->{index} <=> $b->{index} } @hits;",
        "my $hit = $hits[0];",
        "my $start = $hit->{index};",
        "my $end = scalar @lines;",
        "",
        "for (my $i = $start + 1; $i < @lines; $i++) {",
        "    my $line = $lines[$i];",
        "    if ($line =~ /^=cut\\b/) { $end = $i; last; }",
        "    if ($hit->{kind} eq 'item') {",
        "        if ($line =~ /^=item\\b/ || $line =~ /^=back\\b/ || $line =~ /^=head[1-4]\\b/) { $end = $i; last; }",
        "    } else {",
        "        if ($line =~ /^=head([1-4])\\b/) {",
        "            my $level = $1;",
        "            if ($level <= $hit->{level}) { $end = $i; last; }",
        "        }",
        "    }",
        "}",
        "",
        "my $pod = qq{=pod\\n\\n};",
        "if ($hit->{kind} eq 'item') { $pod .= qq{=over 4\\n\\n}; }",
        "$pod .= join('', @lines[$start .. $end - 1]);",
        "if ($hit->{kind} eq 'item') { $pod .= qq{\\n=back\\n}; }",
        "$pod .= qq{\\n=cut\\n};",
        "",
        "my $out = '';",
        "my $parser = Pod::Simple::Text->new;",
        "$parser->output_string(\\$out);",
        "$parser->parse_string_document($pod);",
        "$out =~ s/^\\s+//;",
        "$out =~ s/\\s+$//;",
        "unless (length $out) {",
        "    print STDERR qq{No symbol POD found for \"$symbol\" in \"$module\" for owner \"$owner\".\\n};",
        "    exit 3;",
        "}",
        "print $out, qq{\\n};",
        "exit 0;"
    ].join("\n");
}).apply(module.exports);
